version: '3.8'
services:
  mongo6:
    image: mongo:6.0.12
    container_name: mongo6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
#    volumes: #
#      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
